<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Faculty.aspx.cs" Inherits="ACADPORTAL1.Faculty" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    
    <title>CRUD Operations in GridView</title>
    <style>
        
        .table {
            margin-left: 33.3%;
        }
        body{
            background-image: url('photus/college.jpg');
            background-size: 100%;
            width: 100%;
            font-family: cursive;
        }
        /* styles.css */
            .gridview {
                width: 100%;
                border-collapse: collapse;
                text-align: center;
                background-color:dimgrey;
            }

            .gridview th, .gridview td {
                padding: 10px;
                border: 1px solid #ddd;
            }

            .gridview th {
                background-color: #4CAF50;
                color: white;
            }
            .gridview tr:hover {
                background-color: #ddd;
            }

    </style>
</head>
    
<body>
    <form id="form1" runat="server">
         
            
          <div><h1 style="text-align:center">Faculty Members</h1></div>
             <div>
                 <table class="table"> 
                     <tr>
                         <td>Name:</td>
                         <td><asp:TextBox ID="txtName" runat="server"></asp:TextBox></td>

                     </tr>
                     <tr>
                         <td>Gender:</td> <td><asp:TextBox ID="txtGender" runat="server"></asp:TextBox></td>

                     </tr> 
                     <tr> 
                         <td>Mobile:</td> <td><asp:TextBox ID="txtMobile" runat="server"></asp:TextBox></td>

                     </tr>
                     <tr>
                         <td>Email:</td> <td><asp:TextBox ID="txtEmail" runat="server"></asp:TextBox></td> </tr>
                     <tr> <td>Department:</td> <td><asp:TextBox ID="txtDepartment" runat="server"></asp:TextBox></td> 

                     </tr> <tr> <td colspan="2" style="text-align:center"> <asp:Button ID="btnInsert" runat="server" Text="Add new member" OnClick="btnInsert_Click" /> 
                         </td>

                           </tr> 

                                                </table>
            
        </div>

        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                DataKeyNames="id" 
                DataSourceID="SqlDataSource1" 
                AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" 
                OnRowEditing="GridView1_RowEditing" 
                OnRowCancelingEdit="GridView1_RowCancelingEdit" 
                OnRowUpdating="GridView1_RowUpdating" 
                OnRowDeleting="GridView1_RowDeleting" AllowPaging="True" CssClass="gridview" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"  >
                <Columns>
<asp:BoundField DataField="id" HeaderText="id" SortExpression="id" InsertVisible="False" ReadOnly="True"></asp:BoundField>
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
                    <asp:BoundField DataField="Mobile" HeaderText="Mobile" SortExpression="Mobile" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    <asp:BoundField DataField="Department" HeaderText="Department" SortExpression="Department" />
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource 
                ID="SqlDataSource1" 
                runat="server" 
                ConnectionString="<%$ ConnectionStrings:AcadPortalConnectionString2 %>" 
                SelectCommand="SELECT * FROM [Faculty]"
                InsertCommand="INSERT INTO [Faculty] ([Name], [Gender], [Mobile], [Email], [Department], [Password]) VALUES (@Name, @Gender, @Mobile, @Email, @Department, @Password)"
                UpdateCommand="UPDATE [Faculty] SET [Name] = @Name, [Gender] = @Gender, [Mobile] = @Mobile, [Email] = @Email, [Department] = @Department, [Password] = @Password WHERE [id] = @id"
                DeleteCommand="DELETE FROM [Faculty] WHERE [id] = @id" ProviderName="<%$ ConnectionStrings:AcadPortalConnectionString2.ProviderName %>">
                <InsertParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Gender" Type="String" />
                    <asp:Parameter Name="Mobile" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Department" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Gender" Type="String" />
                    <asp:Parameter Name="Mobile" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Department" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="id" Type="Int32" />
                </UpdateParameters>
                <DeleteParameters>
                    <asp:Parameter Name="id" Type="Int32" />
                </DeleteParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
